DROP TABLE SECURITY_ROLE_USER_ACCOUNT;
DROP TABLE SECURITY_ROLE;
DROP TABLE USER_ACCOUNT_ACCOUNT;
DROP TABLE USER_ACCOUNT;
DROP TABLE ASSET;
DROP TABLE ACCOUNT;
DROP TABLE PORTFOLIO;

CREATE TABLE PORTFOLIO (
    PORTFOLIO_ID INT IDENTITY NOT NULL,
    BALANCE DOUBLE,
    VERSION INTEGER,
    PRIMARY KEY (PORTFOLIO_ID)
);
CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT IDENTITY NOT NULL,
    ACCOUNT_TYPE CHARACTER(1),
    RATE DOUBLE,
    BALANCE DOUBLE,
    VERSION INTEGER,
    PORTFOLIO_ID INTEGER,
    PRIMARY KEY (ACCOUNT_ID)
);
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCNT_PFOLIO_FK 
    FOREIGN KEY(PORTFOLIO_ID) REFERENCES PORTFOLIO(PORTFOLIO_ID);
CREATE TABLE ASSET (
    ASSET_ID INT IDENTITY NOT NULL,
    PORTFOLIO_ID INTEGER,
    PRIMARY KEY (ASSET_ID)
);
ALTER TABLE ASSET ADD CONSTRAINT ASSET_PFOLIO_FK 
    FOREIGN KEY(PORTFOLIO_ID) REFERENCES PORTFOLIO(PORTFOLIO_ID);
CREATE TABLE USER_ACCOUNT (
    USER_ID INT IDENTITY NOT NULL,
    PRIMARY KEY (USER_ID)
);
CREATE TABLE USER_ACCOUNT_ACCOUNT (
    ACCOUNT_ID INT,
    USER_ID INT
);
ALTER TABLE USER_ACCOUNT_ACCOUNT ADD CONSTRAINT UAA_ACCOUNT_FK 
    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);
ALTER TABLE USER_ACCOUNT_ACCOUNT ADD CONSTRAINT UAA_USER_FK 
    FOREIGN KEY(USER_ID) REFERENCES USER_ACCOUNT(USER_ID);
--CREATE TABLE SECURITY_ROLE (
--    ROLE_ID INT IDENTITY NOT NULL,
--    ROLE_NAME VARCHAR,
--    PRIMARY KEY (ROLE_ID)
--);
--CREATE TABLE SECURITY_ROLE_USER_ACCOUNT (
--    ACCOUNT_ID INT,
--    ROLE_ID INT
--);
--ALTER TABLE SECURITY_ROLE_USER_ACCOUNT ADD CONSTRAINT SRUA_USER_ACCOUNT_FK 
--    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);
--ALTER TABLE SECURITY_ROLE_USER_ACCOUNT ADD CONSTRAINT SRUA_SECURITY_ROLE_FK 
--    FOREIGN KEY(ROLE_ID) REFERENCES SECURITY_ROLE(ROLE_ID);
--INSERT INTO SECURITY_ROLE VALUES(0,'ADMIN_ROLE');
--INSERT INTO SECURITY_ROLE VALUES(1,'USER_ROLE');